name: petpet
description: Pet friendly social network 
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  mongo_dart: ^0.10.4
  protobuf: ^4.0.0
  grpc: ^4.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
